const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');document.body.appendChild(canvas);
const S=60,map=Array.from({length:S},(_,z)=>Array.from({length:S},(_,x)=>x===0||z===0||x===S-1||z===S-1?'stone':0)),palette={grass:'#65b84d',dirt:'#9b633b',stone:'#75858b',wood:'#9c6a3d',leaves:'#2f8f45'};
for(let x=3;x<S-3;x++)if(x%3===0)map[8][x]='wood';
for(const[x,z,t]of[[26,25,'grass'],[27,25,'grass'],[28,25,'grass'],[36,17,'stone'],[36,18,'stone'],[36,19,'stone'],[40,37,'wood'],[41,37,'wood'],[21,39,'dirt'],[22,39,'dirt']])map[z][x]=t;
function tree(x,z){map[z][x]='wood';for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(dx||dz)map[z+dz][x+dx]='leaves'}[[10,15],[18,30],[11,43],[31,12],[45,13],[48,29],[46,46],[29,42],[15,52],[52,51]].forEach(([x,z])=>tree(x,z));
const p={x:30.5,z:48.5,a:0,pitch:0,y:0,vy:0,third:false},mobs=[{x:25.5,z:35.5,type:'sheep',d:0},{x:38.5,z:32.5,type:'slime',d:2},{x:22.5,z:44.5,type:'cow',d:4}],keys={},fov=Math.PI/3;
let chosen='grass',locked=false,playing=document.body.dataset.play==='true',last=0,mouseX=null,mouseY=null;
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function cell(x,z){return map[Math.floor(z)]?.[Math.floor(x)]??'stone'}function solid(x,z){return cell(x,z)!==0}function select(t){chosen=t;document.querySelectorAll('.slot').forEach(b=>b.classList.toggle('selected',b.dataset.type===t))}document.querySelectorAll('.slot').forEach(b=>b.addEventListener('click',()=>select(b.dataset.type)));
addEventListener('keydown',e=>{keys[e.code]=true;keys[e.key.toLowerCase()]=true;if(e.code==='Space')e.preventDefault();if(e.code==='KeyP'&&!e.repeat){p.third=!p.third;let view=document.querySelector('#view');if(view)view.textContent=p.third?'Third person':'First person'}if(/^Digit[1-4]$/.test(e.code))select(['grass','dirt','stone','wood'][Number(e.code.at(-1))-1])});addEventListener('keyup',e=>{keys[e.code]=false;keys[e.key.toLowerCase()]=false});canvas.addEventListener('click',()=>canvas.requestPointerLock?.());
const playButton=document.querySelector('#play');if(playButton)playButton.onclick=()=>{playing=true;document.querySelector('#welcome').hidden=true;document.querySelector('#hud').hidden=false;canvas.requestPointerLock?.()};
document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===canvas;mouseX=mouseY=null});document.addEventListener('mousemove',e=>{if(!playing)return;if(locked){p.a+=e.movementX*.0028;p.pitch-=e.movementY*.0028}else{if(mouseX!==null)p.a+=(e.clientX-mouseX)*.006;if(mouseY!==null)p.pitch-=(e.clientY-mouseY)*.006}p.pitch=Math.max(-.75,Math.min(.75,p.pitch));mouseX=e.clientX;mouseY=e.clientY});document.addEventListener('contextmenu',e=>e.preventDefault());
function target(){let x=p.x,z=p.z,dx=Math.sin(p.a)*.08,dz=-Math.cos(p.a)*.08,prev;for(let i=0;i<65;i++){prev={x:Math.floor(x),z:Math.floor(z)};x+=dx;z+=dz;if(solid(x,z))return{hit:{x:Math.floor(x),z:Math.floor(z)},prev}}}document.addEventListener('mousedown',e=>{if(!playing)return;let q=target();if(!q)return;if(e.button===0)map[q.hit.z][q.hit.x]=0;if(e.button===2&&q.prev)map[q.prev.z][q.prev.x]=chosen});
function ray(angle){let d=0;while(d<42){d+=.035;let x=p.x+Math.sin(angle)*d,z=p.z-Math.cos(angle)*d,t=cell(x,z);if(t)return{d,t}}return{d:42,t:0}}
function drawMob(m,horizon){let dx=m.x-p.x,dz=m.z-p.z,dist=Math.hypot(dx,dz),a=Math.atan2(dx,-dz)-p.a;while(a>Math.PI)a-=2*Math.PI;while(a<-Math.PI)a+=2*Math.PI;if(Math.abs(a)>fov*.65||dist>25)return;let sx=innerWidth/2+(a/fov)*innerWidth,h=Math.min(innerHeight*.7,300/dist),w=h*.55,c=m.type==='sheep'?'#f4f0dc':m.type==='cow'?'#75482d':'#57d355',top=horizon-h*.15-p.y*h*.22;ctx.fillStyle=c;ctx.fillRect(sx-w/2,top,w,h*.6);ctx.fillStyle='#172c26';ctx.fillRect(sx-w*.2,top+h*.2,5,5);ctx.fillRect(sx+w*.2-5,top+h*.2,5,5)}
function drawPlayer(){let h=Math.min(220,innerHeight*.34),w=h*.35,x=innerWidth/2-w/2,y=innerHeight-h-20-p.y*45;ctx.fillStyle='rgba(25,40,20,.28)';ctx.fillRect(x-w*.3,y+h-5,w*1.6,10);ctx.fillStyle='#2f6fbc';ctx.fillRect(x,y+h*.34,w,h*.38);ctx.fillStyle='#343b5c';ctx.fillRect(x+w*.05,y+h*.72,w*.36,h*.28);ctx.fillRect(x+w*.59,y+h*.72,w*.36,h*.28);ctx.fillStyle='#bf7d5c';ctx.fillRect(x+w*.12,y,w*.76,h*.3);ctx.fillStyle='#4a2d22';ctx.fillRect(x+w*.07,y-h*.04,w*.86,h*.13);ctx.fillStyle='#1c2b3a';ctx.fillRect(x+w*.23,y+h*.12,w*.12,h*.06);ctx.fillRect(x+w*.65,y+h*.12,w*.12,h*.06)}
function frame(t){requestAnimationFrame(frame);let dt=Math.min(.05,(t-last)/1000||.016);last=t;if(playing){p.a+=((keys.ArrowRight||keys.arrowright?1:0)-(keys.ArrowLeft||keys.arrowleft?1:0))*2.4*dt;if((keys.Space||keys[' '])&&p.y===0){p.vy=6;keys.Space=keys[' ']=false}p.vy-=15*dt;p.y+=p.vy*dt;if(p.y<=0){p.y=0;p.vy=0}let v=3*dt,side=((keys.KeyD||keys.d)?1:0)-((keys.KeyA||keys.a)?1:0),forward=((keys.KeyW||keys.w)?1:0)-((keys.KeyS||keys.s)?1:0),nx=p.x+(Math.sin(p.a)*forward+Math.cos(p.a)*side)*v,nz=p.z+(-Math.cos(p.a)*forward+Math.sin(p.a)*side)*v;if(!solid(nx,p.z))p.x=nx;if(!solid(p.x,nz))p.z=nz;mobs.forEach((m,i)=>{m.d+=Math.sin(t/900+i)*dt;m.x+=Math.cos(m.d)*dt*.5;m.z+=Math.sin(m.d)*dt*.5;if(solid(m.x,m.z)){m.d+=Math.PI;m.x+=Math.cos(m.d)*.1;m.z+=Math.sin(m.d)*.1}})}let horizon=innerHeight/2+p.pitch*innerHeight*.55-p.y*innerHeight*.09;let sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#63b7e8');sky.addColorStop(.72,'#a8ddf0');sky.addColorStop(1,'#d5edda');ctx.fillStyle=sky;ctx.fillRect(0,0,innerWidth,horizon);ctx.fillStyle='#fff2a8';ctx.beginPath();ctx.arc(innerWidth*.78,Math.max(45,horizon*.23),Math.min(42,innerHeight*.06),0,Math.PI*2);ctx.fill();for(let c=0;c<5;c++){let cx=(c*317+(t*.012)%innerWidth)%innerWidth,cy=horizon*.18+(c%3)*28;ctx.fillStyle='rgba(255,255,255,.72)';ctx.fillRect(cx,cy,100,12);ctx.fillRect(cx+20,cy-8,55,20)}ctx.fillStyle='#6fae4b';ctx.fillRect(0,horizon,innerWidth,innerHeight-horizon);let fog=ctx.createLinearGradient(0,horizon,0,horizon+innerHeight*.3);fog.addColorStop(0,'rgba(220,238,205,.42)');fog.addColorStop(1,'rgba(220,238,205,0)');ctx.fillStyle=fog;ctx.fillRect(0,horizon,innerWidth,innerHeight-horizon);for(let y=horizon;y<innerHeight;y+=3){ctx.fillStyle=`rgba(70,70,30,${Math.min(.15,(y-horizon)/innerHeight*.35)})`;ctx.fillRect(0,y,innerWidth,1)}let columns=180,step=innerWidth/columns;for(let i=0;i<columns;i++){let a=p.a-fov/2+fov*i/columns,r=ray(a),d=r.d*Math.cos(a-p.a),h=Math.min(innerHeight*1.5,innerHeight/d),shade=Math.max(.2,1-d/20);ctx.fillStyle=shadeColor(palette[r.t]||'#000',shade);ctx.fillRect(i*step,horizon-h/2-p.y*h*.15,step+1,h)}mobs.slice().sort((a,b)=>Math.hypot(b.x-p.x,b.z-p.z)-Math.hypot(a.x-p.x,a.z-p.z)).forEach(m=>drawMob(m,horizon));if(p.third)drawPlayer()}
function shadeColor(hex,s){let n=parseInt(hex.slice(1),16),r=((n>>16)&255)*s,g=((n>>8)&255)*s,b=(n&255)*s;return`rgb(${r|0},${g|0},${b|0})`}requestAnimationFrame(frame);
